kind: pipeline
type: kubernetes
name: default



platform:
  os: linux
  arch: arm64

clone:
  disable: true
  

steps:
- name: clone
  image: bitnami/git
  commands:
  - sleep 2
  - git clone https://github.com/yuexclusive/foo.git
  # - git checkout $DRONE_COMMIT

- name: greeting
  image: alpine
  commands:
  - echo hello
  - echo world
  - pwd
  - ls

- name: build
  image: golang:alpine
  commands:
  - go build -o test ./foo
  - ls -l test