kind: pipeline
type: kubernetes
name: default



platform:
  os: linux
  arch: arm64

clone:
  disable: true
  

steps:
- name: clone
  image: bitnami/git
  commands:
  - sleep 0.8
  - git clone https://github.com/yuexclusive/foo.git
  # - git checkout $DRONE_COMMIT

- name: greeting
  image: alpine
  commands:
  - echo hello
  - echo world
  - pwd
  - ls

- name: build
  image: golang:alpine
  commands:
  - cd foo
  - go build -o test .
  - ls -l


- name: fuck
  image: golang:alpine
  commands:
  - pwd