kind: pipeline
type: kubernetes
name: default

clone:
  disable: true


steps:
- name: clone
  image: bitnami/git


- name: greeting
  image: alpine
  commands:
  - pwd
  - ls -a
  - echo hello
  - echo world