kind: pipeline
type: kubernetes
name: default



platform:
  os: linux
  arch: arm64

clone:
  disable: true
  

steps:
- name: clone
  image: bitnami/git
  commands:
  - sleep 2
  - git clone https://github.com/yuexclusive/foo.git
  # - git checkout $DRONE_COMMIT

- name: build
  image: golang:1.18beta1-alpine3.15
  commands:
  - cd foo
  - go build -o test .

- name: publish
  image: docker
  commands:
  - docker build --rm -t yuexclusive/test:latest .
  - docker publish yuexclusive/test:latest