kind: pipeline
type: kubernetes
name: default



platform:
  os: linux
  arch: arm64

clone:
  disable: true
  

steps:
- name: clone
  image: alpine/git
  commands:
  - cat >> /etc/sysctl.conf <<EOF
    net.ipv4.ip_forward=1
    EOF
    sysctl -p >/dev/null 2>&1
    echo "nameserver 8.8.8.8">/etc/resolv.conf
  - git clone https://github.com/yuexclusive/foo.git/ .
  - git checkout $DRONE_COMMIT

- name: greeting
  image: alpine
  commands:
  - echo hello
  - echo world