kind: pipeline
type: kubernetes
name: default

clone:
  disable: true


steps:
- name: clone
  image: bitnami/git
  commands:
  - git clone https://github.com/yuexclusive/foo.git

# - name: build
#   image: bitnami/golang
#   commands:
#   - go build

# - name: greeting
#   image: alpine
#   commands:
#   - pwd
#   - ls -a
#   - echo hello
#   - echo world