kind: pipeline
type: kubernetes
name: default



platform:
  os: linux
  arch: arm64

clone:
  disable: true
  

steps:
- name: clone
  image: bitnami/git
  commands:
  - sleep 10
  - echo start
  - apt update
  - curl www.baidu.com
  - git clone https://github.com/yuexclusive/foo.git
  # - git checkout $DRONE_COMMIT

- name: greeting
  image: alpine
  commands:
  - echo hello
  - echo world